# Generated by Django 3.2.9 on 2021-11-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='score',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
