# Generated by Django 3.2.9 on 2021-11-24 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_max_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='max_students',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)]),
        ),
    ]
